# Generated by Django 3.1.5 on 2021-01-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d', verbose_name='Аватар пользователя'),
        ),
    ]
